#### general settings
gpus: [0,1]
log_freq: 100
exp_name: RAFT-cvo

#### training settings

# We finetune on the combined clean and final passes of the training set, with ~100K iters.
epochs: 60 
valid_freq: 1000 # iters
lr: !!float 1.2e-4
wdecay: !!float 1.0e-5
epsilon: !!float 1.0e-8
mixed_precision: true
batch_per_gpu: 6
# Above settings follow the RAFT.

clip: 1.0
image_size: [256, 256]
add_noise: true
loss_type: L1
prefetch: false

#### dataset settings
train_sample: ~
valid_sample: 500
visual_samples: [0, 1, 2]
